export const REQUEST_INITIAL_LIST = 'REQUEST_INITIAL_LIST';

export const REQUEST_INITIAL_LIST_SUCCESS = 'REQUEST_INITIAL_LIST_SUCCESS';

export const SAVE_SEARCH_FIELD = 'SAVE_SEARCH_FIELD';

export const SAVE_CATEGORY_FIELD = 'SAVE_CATEGORY_FIELD';

export const REQUEST_INITIAL_CATEGORY_API_SUCCESS = 'REQUEST_INITIAL_CATEGORY_API_SUCCESS';

export const NEW_ITEM_CART = 'NEW_ITEM_CART';

export const ADD_QUANTITY = 'ADD_QUANTITY';

export const ADD_CATEGORY_NAME = 'ADD_CATEGORY_NAME';

export const RESET_FILTER = 'RESER_FILTER';

export const CHANGE_EXIBITION_MODE = 'CHANGE_EXIBITION_MODE';

export const ADD_TOTAL_CHECKOUT = 'ADD_TOTAL_CHECKOUT';

export const RESET_TOTAL_CHECKOUT = 'RESET_TOTAL_CHECKOUT';

export const DELETE_ITEM = 'DELETE_ITEM'
