export const REQUEST_INITIAL_LIST = 'REQUEST_INITIAL_LIST';

export const REQUEST_INITIAL_LIST_SUCCESS = 'REQUEST_INITIAL_LIST_SUCCESS';

export const SAVE_SEARCH_FIELD = 'SAVE_SEARCH_FIELD';

export const SAVE_CATEGORY_FIELD = 'SAVE_CATEGORY_FIELD';

export const REQUEST_INITIAL_CATEGORY_API_SUCCESS = 'REQUEST_INITIAL_CATEGORY_API_SUCCESS';

export const NEW_ITEM_CART = 'NEW_ITEM_CART';

export const ADD_QUANTITY = 'ADD_QUANTITY';
